name: Ansible CD - CharlenesCoffeeCorner 
on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  Deploy-CharlenesCoffeeCorner:
    runs-on: ubuntu-latest
    steps:
      - name: Set ssh private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with: 
          workflow: CharlenesCoffeeCorner-CI.yaml
          repo: red-devops/CharlenesCoffeeCorner
          
      - name: Install required software
        run: |
          sudo pip install boto3 ansible 
          ansible-galaxy install -r requirements.yaml
      
      - name: Run Ansible Playbook
        run: |
          /usr/local/bin/ansible-playbook -i inventory_aws_ec2.yaml deploy-playbook.yaml --extra-vars="workspace_path=$GITHUB_WORKSPACE" -v
